### ISSUE TITLE
PHP 8.4 Update - E_STRICT is deprecated warning

### ISSUE THREAD

**Issue by boan-jfm** [mindplay-dk/readable#4]
> Because the [E_STRICT](https://www.php.net/manual/en/errorfunc.constants.php#constant.e-strict) error level was removed, this constant is now deprecated.
>-- https://www.php.net/manual/en/migration84.deprecated.php

Code deprecation:
https://github.com/mindplay-dk/readable/blob/1.2.2/src/readable.php#L48

**Comment by mindplay-dk** [comment]
What would you suggest we do about it?

Simply removing this would be a breaking change for anything below 8.4, so probably not acceptable.

We could put in `2048` as the literal value for backwards compatibility maybe?

(also, deprecating a constant? legit weird. deprecate passing that value to certain functions, sure, but deprecating... a constant? that is such a PHP thing to do 😛)

**Comment by boan-jfm** [comment]
For the long run, I would suggest removing it and adding PHP `^8.4` as a dependency (https://github.com/mindplay-dk/readable/blob/1.2.2/composer.json#L7).

If you would like to have backwards compatibility, it would be fine to add `2048` as a literal value and keep PHP `^8.0` as a dependency.

**Comment by mindplay-dk** [comment]
More work was required to get this building with PHP 8.4, but I've tagged a new release.

Note the license change to MPL-2.0.
